sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t itamarb1/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true itamarb1/docker-react1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react1"
  env: "Dockerreact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-405992272368"
  bucket_path: "docker-react1"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"
