sudo: required
language: generic
services:
  - docker

  before_install:
    - docker build -t itamarb1/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true itamarb1/docker-react1 npm run test

